// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_app from "./routes/_app.tsx";
import * as $api_calculations_nodeId_ from "./routes/api/calculations/[nodeId].ts";
import * as $api_graph_edges from "./routes/api/graph/edges.ts";
import * as $api_ingredients from "./routes/api/ingredients.ts";
import * as $api_inventories from "./routes/api/inventories.ts";
import * as $api_inventories_id_ from "./routes/api/inventories/[id].ts";
import * as $api_inventories_id_activate from "./routes/api/inventories/[id]/activate.ts";
import * as $api_inventories_id_save_stocks from "./routes/api/inventories/[id]/save-stocks.ts";
import * as $api_inventories_id_stocks from "./routes/api/inventories/[id]/stocks.ts";
import * as $api_inventories_active from "./routes/api/inventories/active.ts";
import * as $api_production_execute from "./routes/api/production/execute.ts";
import * as $api_production_max from "./routes/api/production/max.ts";
import * as $api_production_orders_id_ from "./routes/api/production/orders/[id].ts";
import * as $api_production_orders_index from "./routes/api/production/orders/index.ts";
import * as $api_production_simulate from "./routes/api/production/simulate.ts";
import * as $api_products from "./routes/api/products.ts";
import * as $api_recipes from "./routes/api/recipes.ts";
import * as $api_stock from "./routes/api/stock.ts";
import * as $api_stock_transact from "./routes/api/stock/transact.ts";
import * as $index from "./routes/index.tsx";
import * as $CostTimeBreakdown from "./islands/CostTimeBreakdown.tsx";
import * as $EntityEditor from "./islands/EntityEditor.tsx";
import * as $EntityManager from "./islands/EntityManager.tsx";
import * as $ProductionOrdersPanel from "./islands/ProductionOrdersPanel.tsx";
import * as $ProductionSimulator from "./islands/ProductionSimulator.tsx";
import * as $StockDashboard from "./islands/StockDashboard.tsx";
import * as $Workspace from "./islands/Workspace.tsx";
import * as $workspace_InventoryPopover from "./islands/workspace/InventoryPopover.tsx";
import * as $workspace_useWorkspaceData from "./islands/workspace/useWorkspaceData.ts";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_app.tsx": $_app,
    "./routes/api/calculations/[nodeId].ts": $api_calculations_nodeId_,
    "./routes/api/graph/edges.ts": $api_graph_edges,
    "./routes/api/ingredients.ts": $api_ingredients,
    "./routes/api/inventories.ts": $api_inventories,
    "./routes/api/inventories/[id].ts": $api_inventories_id_,
    "./routes/api/inventories/[id]/activate.ts": $api_inventories_id_activate,
    "./routes/api/inventories/[id]/save-stocks.ts":
      $api_inventories_id_save_stocks,
    "./routes/api/inventories/[id]/stocks.ts": $api_inventories_id_stocks,
    "./routes/api/inventories/active.ts": $api_inventories_active,
    "./routes/api/production/execute.ts": $api_production_execute,
    "./routes/api/production/max.ts": $api_production_max,
    "./routes/api/production/orders/[id].ts": $api_production_orders_id_,
    "./routes/api/production/orders/index.ts": $api_production_orders_index,
    "./routes/api/production/simulate.ts": $api_production_simulate,
    "./routes/api/products.ts": $api_products,
    "./routes/api/recipes.ts": $api_recipes,
    "./routes/api/stock.ts": $api_stock,
    "./routes/api/stock/transact.ts": $api_stock_transact,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/CostTimeBreakdown.tsx": $CostTimeBreakdown,
    "./islands/EntityEditor.tsx": $EntityEditor,
    "./islands/EntityManager.tsx": $EntityManager,
    "./islands/ProductionOrdersPanel.tsx": $ProductionOrdersPanel,
    "./islands/ProductionSimulator.tsx": $ProductionSimulator,
    "./islands/StockDashboard.tsx": $StockDashboard,
    "./islands/Workspace.tsx": $Workspace,
    "./islands/workspace/InventoryPopover.tsx": $workspace_InventoryPopover,
    "./islands/workspace/useWorkspaceData.ts": $workspace_useWorkspaceData,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
